version: '3'

services:
  backend:
    build: ./serviceapi
    privileged: true
    ports:
      - 8080:8080
    command:
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8080

  frontend:
    build: ./serviceapi/frontend
    privileged: true
    ports:
      - 80:80
    command:
      - npm run dev