# Generated by Django 4.1.1 on 2022-09-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ticket_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-deliv_data'], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='creat_content',
            new_name='deliv_data',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='Delivered',
            new_name='delivered',
        ),
    ]
