# Generated by Django 4.1.1 on 2022-09-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='deliv_data',
            field=models.CharField(max_length=250, verbose_name='Cрок поставки'),
        ),
    ]
