# Generated by Django 4.1.1 on 2022-10-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ticket_options_rename_title_ticket_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-pk'], 'verbose_name': 'Order', 'verbose_name_plural': 'Order'},
        ),
    ]
